import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../../public/imagemeu.png';
import design from '../../public/design.png';
import code from '../../public/code.png';
import consulting from '../../public/consulting.png';
import web1 from '../../public/web1.png';
import web2 from '../../public/web2.png';
import web3 from '../../public/web3.png';
import web4 from '../../public/web4.png';
import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Wisley A. Sousa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 '>
        <section
          className="min-h-screen ">
            <nav className='drop-shadow-lg py-5 mb-12 flex justify-between px-20 fixed top-0 left-0 right-0 bg-gradient-to-r from-cyan-50 via-gray-50 to-cyan-50 rounded-full'>
              <h1 className='text-xl hover:drop-shadow-xl hover:backdrop-blur-sm hover:cursor-pointer italic font-burtons font-semibold '>Portfolio</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-xl '/>
                </li>
                <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 font-semibold hover:shadow-cyan-500/50 hover:drop-shadow-xl hover:from-cyan-800 hover:to-teal-300 ' href='./'>Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-4xl py-2 text-teal-700 hover:opacity-50 md:text-6xl truncate hover:text-clip font-medium hover:shadow-cyan-800/200 hover:cursor-pointer pt-20 dark:text-teal-300'>Wisley A. Sousa</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-200'>Front-end Developer</h3>
              <p className='text-md py-5 leading-6 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.</p>
            </div>
            <div className='text-4xl flex justify-center gap-12 py-2 text-gray-600'>
              <a href='https://www.linkedin.com/in/wisley-a-sousa-843060a2/' className='hover:cursor-pointer hover:text-black hover:dark:text-white' target="_blank" rel="noreferrer">
                <AiFillLinkedin />
              </a>
              <a href='https://github.com/WisleyASousa' className='hover:cursor-pointer hover:text-black hover:dark:text-white' target="_blank" rel="noreferrer">
                <AiFillGithub />
              </a>
            </div>
            <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-40 mt-10 mx-auto'>
              <Image src={deved} alt='developer' />
            </div>
        </section>

        <section>
          <div className='text-center'>
            <h3 className='text-2xl pt-1 py-1 dark:text-gray-200'>Services I offer</h3>
            <p className='text-md py-2 leading-6 text-justify text-gray-800 dark:text-gray-200'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum <span className='text-teal-500'>dolor </span> sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.
            </p>
            <p className='text-md py-2 leading-6 text-justify text-gray-800 dark:text-gray-200'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum <span className='text-teal-500'>dolor </span> sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.
            </p>
          </div>
          <div className='md:flex gap-10'>
            <div className='text-center bg-gradient-to-r from-cyan-50 to-teal-200 shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100} alt={''} className='mx-auto' />
              <h3 className='text-lg font-medium pt-6 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.
              </p>
              <h4 className='py-4 text-teal-900'>Desgin tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center bg-gradient-to-r from-cyan-50 to-teal-200 shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100} alt={''} className='mx-auto' />
              <h3 className='text-lg font-medium pt-6 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.
              </p>
              <h4 className='py-4 text-teal-900'>Desgin tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center bg-gradient-to-r from-cyan-50 to-teal-200 shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100} alt={''} className='mx-auto' />
              <h3 className='text-lg font-medium pt-6 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.
              </p>
              <h4 className='py-4 text-teal-900'>Desgin tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div></div>
          </div>
        </section>
        <section>
          <div className=''>
            <h3 className='text-3xl pt-2 py-1 dark:text-gray-200 text-center'>Portfolio</h3>
            <p className='text-md py-2 leading-6 text-justify text-gray-800 dark:text-gray-200'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum <span className='text-teal-500'>dolor </span> sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.
            </p>
            <p className='text-md py-2 leading-6 text-justify text-gray-800 dark:text-gray-200'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum <span className='text-teal-500'>dolor </span> sit amet consectetur adipisicing elit. Quisquam, quae.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quae.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 md:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1 '>
              <Image src={web1} alt={''} className='rounded-xl object-cover' width={500} />
            </div>
            <div className='basis-1/3 flex-1 '>
              <Image src={web2} alt={''} className='rounded-xl object-cover' width={500} />
            </div> 
            <div className='basis-1/3 flex-1 '>
              <Image src={web3} alt={''} className='rounded-xl object-cover' width={500} />
            </div>
            <div className='basis-1/3 flex-1 '>
              <Image src={web4} alt={''} className='rounded-xl object-cover' width={500} />
            </div>
          </div>
        </section>
      </main>
      <footer>
        <div>
          <p className='drop-shadow-lg text-center py-2 font-burtons px-20 bg-gradient-to-r from-cyan-50 via-gray-50 to-cyan-50 rounded-full'>Wisley A. Sousa - Picos, PI - 2022</p>
        </div>
      </footer>

    </div>
  )
}
